name: Build

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install
        run: npm install -s
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          APP_ENV: ci
          BOWERY_APP_DOMAIN: https://bowery-development.herokuapp.com
          GOOGLE_API_KEY: ${{secrets.GOOGLE_API_KEY}}
          AMPLITUDE_API_KEY: ${{secrets.CI_AMPLITUDE_KEY}}
          GENERATE_ARTIFACT: false
      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v2
        with:
          name: BoweryChromeExtension
          path: build/*